# Generated by Django 4.0.5 on 2022-06-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_categories_alter_user_first_name_listings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
        ),
    ]
