# Generated by Django 2.2 on 2022-06-12 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220612_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='author',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ManyToManyField(null=True, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
