# Generated by Django 2.2 on 2022-06-12 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220612_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Cancelled'), (3, 'Sold')], default=1),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='listinings', to='auctions.Categories'),
        ),
    ]
