# Generated by Django 4.0.5 on 2022-06-21 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
