# Generated by Django 2.2 on 2022-06-12 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220612_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='author',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
