# Generated by Django 2.2 on 2022-06-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highest_bid',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='listings', to='auctions.Bids'),
        ),
    ]
