# Generated by Django 2.2 on 2022-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
